### ISSUE TITLE
Colorlight firmware

### ISSUE THREAD

**Issue by rik-coenders** [haraldkubota/colorlight#4]
Dear haraldkuboata,

I have been very inspired by the software you wrote to control my own led panels as well.

I have a question that might be a bit strange. But the the thing that I built based on your example works very well on the LED panels I had. Lately I ordered more LED panels and there the code does no longer work. They use the same chip but I think they might have a newer firmware version.

I tested with LedVision in combination with wireshark. With Ledvision it is possible to control the led screens sucesfully. I cannot find any differences in the packages that are being sent between Ledvision and the packages being sent from your code.

So my question would be, do you have any idea in what direction I could look for finding the solution?

Thanks in advance.

**Comment by haraldkubota** [comment]
If you have different panels and different resolutions, then I cannot say what is wrong, but I can say that I only tested for a 128x64 panel. I do not have panels for more pixels. If you have a higher resolution, then it would be great to know which one it is as that might explain.

That said, since you talk about "new firmware version": are we talking about more panels or a new receiver card here?

If it's about the receiver card, then that is the problem with a non-documented reverse-engineered protocol: it might change with the next update or new products might simply not work. Maybe that happened here, but you should see then differences in the Wireshark dump. Check the very beginning (detection, initialization) differences between old and new controller.

**Comment by rik-coenders** [comment]
Hi, thanks for the quick reply.

I now managed to put the old firmware on the other panels, and that solves the problem. Because you might be interested I will explain what I have anyway:

I use LED panels with the Colorlight E80 chip, which is basically the same as the 5A 75. Both the old and new panels have this chip, but with different firmware versions. 

We have panels of 128 by 96 pixels, and we combine 4 of them together in a 2x2 configuration, which works well (on the old firmware). The configuring of the panels itself into having the right panel at the right place is done with LedVision.

I understand that the protocol can change anytime between firmware versions, as it is not documented and open for extension. But the strange thing is, that when I look with Wireshark what LedVision is sending to panels with the new firmware it is exactly the same. I cannot find any differences.

For now I can work with the old firmware, but I will try with the new firmware soon again just to try and see if I can find it. Not because I need it, but just because I am curious. If I find what it is I will let you know.

**Comment by haraldkubota** [comment]
Thanks for those additional details.  I was not aware that there is a new (smaller) version of the 5A 75B available. I see the E80 is cheaper than the 5A 75B (size matters!), so I'll get one for me to try to find out what's going on here. 

It's good to know that the firmware is backward compatible though. Thanks for testing that!

For now I'll close this thread since there is a solution (using the older firmware), but if you find a difference (or I do), I'll update the code accordingly. Or at least the documentation.
