### ISSUE TITLE
5a-75b v8 no answer 

### ISSUE THREAD

**Issue by jgaetev** [haraldkubota/colorlight#6]
Hello, first of all, thank you for publishing this information. I am trying to communicate with a 5a-75b v8.0, first trying with your detect.py module but I do not receive any response, after the socket timeout I receive in data[12] an 8 and in data[13] a 0. 
This card is configured with the sw. ledvision (works perfectly) for 128x64 modules.
I would appreciate any advice or help.

**Comment by haraldkubota** [comment]
Hi,

not sure I can help, but I found it most useful to do wireshark capturing to see what data goes out and what data comes back (if anything comes back). My first tries didn't work because I were using the wrong NIC. Wireshark made that very easy to debug: ledvision worked and was sending a ton of data over, but my program did not.
Also in case you don't use Linux: no guarantee anything works on non-Linux: I have not tested Windows at all. Or any other OS for that matter.

**Comment by jgaetev** [comment]
Hello Harald, I hadn't seen your answer, the issue was that I was using wsl (linux for windows), but I connected to an orangepi directly and it worked perfectly !
